name: Cleanup PR Comments

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete PR comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const repo = context.repo;
            
            console.log(`Cleaning up comments for PR #${pr_number}`);
            
            // Get all issue comments (general PR comments)
            const issueComments = await github.rest.issues.listComments({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: pr_number,
            });
            
            console.log(`Found ${issueComments.data.length} issue comments`);
            
            // Delete issue comments from the bot - match any of these phrases
            let deletedIssueComments = 0;
            for (const comment of issueComments.data) {
              console.log(`Comment ${comment.id} by ${comment.user.login}`);
              if (comment.user.login === 'github-actions[bot]' && 
                  (comment.body.includes('Automated LLM Code Review') ||
                   comment.body.includes('Executive Code Review') ||
                   comment.body.includes('Powered by Snowflake Cortex AI'))) {
                console.log(`Deleting issue comment ${comment.id}`);
                await github.rest.issues.deleteComment({
                  owner: repo.owner,
                  repo: repo.repo,
                  comment_id: comment.id,
                });
                deletedIssueComments++;
              }
            }
            
            console.log(`Deleted ${deletedIssueComments} issue comments`);
            
            // Get all review comments (inline comments)
            const reviewComments = await github.rest.pulls.listReviewComments({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: pr_number,
            });
            
            console.log(`Found ${reviewComments.data.length} review comments`);
            
            // Delete review comments from the bot - match any of these phrases
            let deletedReviewComments = 0;
            for (const comment of reviewComments.data) {
              console.log(`Review comment ${comment.id} by ${comment.user.login}`);
              if (comment.user.login === 'github-actions[bot]' && 
                  (comment.body.includes('Generated by automated LLM code review') ||
                   comment.body.includes('CRITICAL ISSUE') ||
                   comment.body.includes('Recommendation:'))) {
                console.log(`Deleting review comment ${comment.id}`);
                await github.rest.pulls.deleteReviewComment({
                  owner: repo.owner,
                  repo: repo.repo,
                  comment_id: comment.id,
                });
                deletedReviewComments++;
              }
            }
            
            console.log(`Deleted ${deletedReviewComments} review comments`);
            console.log(`Cleanup completed: ${deletedIssueComments} issue comments + ${deletedReviewComments} review comments deleted`);
