name: Cleanup PR Comments

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete PR comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const repo = context.repo;
            
            console.log(`Cleaning up comments for PR #${pr_number}`);
            
            // Get all issue comments (general PR comments)
            const issueComments = await github.rest.issues.listComments({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: pr_number,
            });
            
            // Delete issue comments from the bot
            for (const comment of issueComments.data) {
              if (comment.user.login === 'github-actions[bot]' && 
                  comment.body.includes('Automated LLM Code Review')) {
                console.log(`Deleting issue comment ${comment.id}`);
                await github.rest.issues.deleteComment({
                  owner: repo.owner,
                  repo: repo.repo,
                  comment_id: comment.id,
                });
              }
            }
            
            // Get all review comments (inline comments)
            const reviewComments = await github.rest.pulls.listReviewComments({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: pr_number,
            });
            
            // Delete review comments from the bot
            for (const comment of reviewComments.data) {
              if (comment.user.login === 'github-actions[bot]' && 
                  comment.body.includes('Generated by automated LLM code review')) {
                console.log(`Deleting review comment ${comment.id}`);
                await github.rest.pulls.deleteReviewComment({
                  owner: repo.owner,
                  repo: repo.repo,
                  comment_id: comment.id,
                });
              }
            }
            
            console.log('Cleanup completed');
